application:
  name: handle-system

mongodb:
  host: ds261745.mlab.com
  port: 61745
  database: handlesystem
  username: kacper
  password: kacper
  socketTimeout: 2000

smsClient:
  client: fake

origins:
  github: https://biotplatform.github.io
  localhost: http://localhost:3000